# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Etc/UTC"
    versioning-strategy: increase
    allow:
      - dependency-name: "cspell"
      - dependency-name: "husky"
      - dependency-name: "mint"
    ignore:
      - dependency-name: "remark*"
      - dependency-name: "unified*"
      - dependency-name: "unist*"
      - dependency-name: "mdast*"
      - dependency-name: "*string*"
